### PR TITLE
Remove ansi codes in script run silent mode

### PR DESCRIPTION
**Pull request by istarkov**
ref #3131

### CODE REVIEW

**Comment by istarkov** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rubenfiszel** [comment]
Thanks for the PR, i'm not sure this is the right approach. Is there no way to patch the logger to not use ansi code instead of forking to console.log ?

**Comment by istarkov** [comment]
Data goes to stdout, bypassing the logger since it's not log-related. It's data which can be used for processing like in most cli tools.

Anyway:

In most cli utilities I know all information messages goes to stderr and essential data needed for piping goes to stdout.

Example:
```bash
# highlight stderr
command 2> >(while read line; do echo -e "\e[01;31m$line\e[0m" >&2; done) curl -v https://example.com
```
Result:
image

See all info messages are in stderr.

For windmill all logs are sent to stdout. 

Better would be output all cli util information messages into stderr. And output essential data like script result into stdout. Bypassing the logger like I did too. But this must be done for every ustility in the app.

**Comment by rubenfiszel** [comment]
I think it's debatable if wmill cli logs should go to stdout or stderr (since wmill is not meant to be pipable) and besides the point of this specific feature.

My point is that we have one level of indirection with the logger that is fully configurable: https://deno.land/std@0.214.0/log/mod.ts

The removal of ansi codes should be done by customizing the formatter there rather than skipping entirely the logger since it will not compose well, were we to want to do further log customization

**Comment by istarkov** [comment]
This would be formatter for the whole logs, and technicaly this is not log ;-).  Logs can be redirected to files, http endpoints etc. Here logs are disabled using silent flag, and again it's raw response. 

> since wmill is not meant to be pipable
what the reason to have `wmill script run` and do not allow std unix operations?

**Comment by rubenfiszel** [comment]
I apologize, I read the PR wrong. I thought this was disabling the whole log

**Pull request merged**
