### PR TITLE
feat(front): Confirmation modal when deleting a resource or a variable

### PR DESCRIPTION
**Pull request by fatonramadani**
https://user-images.githubusercontent.com/456655/193264399-b1faaa45-acf8-4ee6-8d92-f38161449cf9.mov

### CODE REVIEW

**Comment by rubenfiszel** [comment]
Can you do the shift thing with tooltip such that it doesn't require confirmation ?

**Comment by fatonramadani** [comment]
> Can you do the shift thing with tooltip such that it doesn't require confirmation ?

Sure!

**Comment by fatonramadani** [comment]
@rubenfiszel I can now press shift to bypass confirmation

**Comment by rubenfiszel** [comment]
Still need to add a tooltip in the modal itself to tip users that they can do that

**Pull request merged**
