### PR TITLE
Add support for dependabot

### PR DESCRIPTION
**Pull request by gaby**
This PR adds support for keeping dependencies up-to-date using dependabot.

Added the following checks:
- Github Actions
- Docker
- Cargo
- npm
- poetry (github uses pip name for this)

Once a dependency becomes outdated, dependabot will auto-create a PR, it's up to the maintainers to approve/merge this PR.

### CODE REVIEW

**Comment by gaby** [comment]
I just tested this PR on my fork, and it created the following 15 PR's:

image

**Comment by rubenfiszel** [comment]
Thanks for the contribution. Looks good to me! You would be the first external contributor and I have just setup a CLA process. Would you be ok going through it by following the bot instruction above ?

**Review by rubenfiszel — APPROVED** [review]

**Comment by gaby** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gaby** [comment]
@rubenfiszel Great to hear, I got a couple ideas I may submit PR's for. Looking forward to using Windmill 😁

**Review by rubenfiszel — APPROVED** [review]

**Pull request merged**
