### PR TITLE
toggle self-signed certs support in oauth2 using env variable ACCEPT_INVALID_CERTS

### PR DESCRIPTION
**Pull request by mingfang**
This is required when integrating Windmill with oauth2 providers using self-signed certs.

### CODE REVIEW

**Comment by mingfang** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mingfang** [comment]
recheck

**Comment by rubenfiszel** [comment]
We need to add this to the README as well with the rest of the env variables

**Comment by mingfang** [comment]
> We need to add this to the README as well with the rest of the env variables

done

**Comment by rubenfiszel** [comment]
Thanks!

**Pull request merged**
