### PR TITLE
WIP: Add MyFitnessPal OAuth Connect definition

### PR DESCRIPTION
**Pull request by Jberlinsky**
Pending local testing

### CODE REVIEW

**Comment by Jberlinsky** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Jberlinsky** [comment]
recheck

**Comment by rubenfiszel** [comment]
This looks great. Thanks a lot for the contribution. Just to make sure, this is something you've been able to test locally ? Would you be open to add the associated resource type to the hub ? :)

https://hub.windmill.dev/integrations/myfitnesspal

**Comment by Jberlinsky** [comment]
@rubenfiszel This hasn't been tested locally quite yet -- I've tagged it as `WIP` for now. Sorry for the confusion.

**Comment by rubenfiszel** [comment]
Closing before being tested

**Pull request closed without merging**
