### PR TITLE
Fixed Typos and Formatting inside README.md File.

### PR DESCRIPTION
**Pull request by rutviklhase**
I came across a few typos and formatting problems when going through the README.md file. 
This PR will fixes the ones I found -

- The Title of each item inside "Main Concepts" has been given proper emphasis. 
     
image

- Fixed a few typos I came across.

Please let me know if there's anything else I should include in this PR! Also let me know if something doesn't look right. 
Thanks!

### CODE REVIEW

**Comment by rutviklhase** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rutviklhase** [comment]
recheck

**Comment by rubenfiszel** [comment]
Not a fan of the bullet point as titles

**Comment by rutviklhase** [comment]
> Not a fan of the bullet point as titles

@rubenfiszel  No problem! We can revert that back to the way it was. 
Thanks for the feedback!

**Pull request closed without merging**
