### PR TITLE
feat(front): Add a confirmation modal

### PR DESCRIPTION
**Pull request by fatonramadani**
https://user-images.githubusercontent.com/456655/192803860-5f746248-723e-4d5e-a655-f8fb26709bda.mov

### CODE REVIEW

**Comment by fatonramadani** [comment]
@rubenfiszel I was thinking of something like that, wdyt ?

**Comment by lplit** [comment]
Looks good!

**Comment by rubenfiszel** [comment]
Look and feel is amazing.

1. It seems that it wouldn't trigger on the minimap
2. we should make it not confirm if the module is empty "Select a script" or if shift is pressed.

**Comment by rubenfiszel** [comment]
Also we should add as a tip to press shift to skip the confirmation pop-up inside the confirmation pop-up

**Comment by fatonramadani** [comment]
@rubenfiszel I've added:
- The SHIFT shorcut ( see video)
- Add support in the minimap
- Removing a empty module doesn't require confirmation

**Pull request merged**
