### PR TITLE
fix: correct exception handling in PHP wrapper

### PR DESCRIPTION
**Pull request by klees**
The `catch` is hinting on [`\Exception`](https://www.php.net/manual/de/class.exception.php) which has not `getName`-method. To identify the type of exception, `get_class` can be used.

----

| :rocket: | This description was created by [Ellipsis](https://www.ellipsis.dev) for commit 0996727aaf823d925795711b841a997e87084fd6  | 
|--------|--------|

### Summary:
This PR updates the PHP wrapper's exception handling by replacing the non-existent `getName` method with `get_class` to correctly retrieve the exception type.

**Key points**:
- Updated exception handling in `backend/windmill-worker/src/php_executor.rs`.
- Replaced `getName` with `get_class` for retrieving exception type in PHP wrapper.

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by klees** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by klees** [comment]
recheck

**Comment by rubenfiszel** [comment]
@HugoCasa can you review this please

**Comment by HugoCasa** [comment]
@klees Thanks for your contribution!
@rubenfiszel Tested and approved

**Pull request merged**
